#!/usr/bin/env node
// Dev-only vendoring tool (NOT an app build step — the app stays one static file).
// Generates @font-face rules with base64-inlined latin woff2 from @fontsource/* and
// rewrites lesson-studio.html in place to:
//   1. replace the Google Fonts <link>/preconnects with a self-contained <style> block
//      (between VENDORED-FONTS markers — idempotent, re-runnable), and
//   2. point the model-viewer <script type="module"> at the local vendored copy.
// Inlining base64 keeps both the app AND exported standalone lessons font-complete with
// zero external files. Re-run after changing the font set below.
//
//   node scripts/vendor-fonts.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FS = path.join(root, 'node_modules', '@fontsource');
const APP = path.join(root, 'lesson-studio.html');

// Exactly the families/weights that were in the Google Fonts <link>.
const FONTS = [
  ['Hanken Grotesk', 'hanken-grotesk', [['400', 'normal'], ['500', 'normal'], ['600', 'normal'], ['700', 'normal']]],
  ['EB Garamond',    'eb-garamond',    [['400', 'normal'], ['500', 'normal'], ['600', 'normal'], ['400', 'italic'], ['500', 'italic']]],
  ['Space Grotesk',  'space-grotesk',  [['500', 'normal'], ['600', 'normal'], ['700', 'normal']]],
  ['Marcellus',      'marcellus',      [['400', 'normal']]],
  ['Cinzel',         'cinzel',         [['500', 'normal'], ['600', 'normal']]],
  ['Fraunces',       'fraunces',       [['500', 'normal'], ['600', 'normal']]],
  ['Oswald',         'oswald',         [['500', 'normal'], ['600', 'normal'], ['700', 'normal']]],
  ['Archivo Narrow', 'archivo-narrow', [['600', 'normal'], ['700', 'normal']]],
  ['Source Serif 4', 'source-serif-4', [['400', 'normal'], ['400', 'italic']]],
  ['Courier Prime',  'courier-prime',  [['400', 'normal'], ['700', 'normal']]],
];

let css = '';
let total = 0;
for (const [family, pkg, faces] of FONTS) {
  for (const [weight, style] of faces) {
    const file = path.join(FS, pkg, 'files', `${pkg}-latin-${weight}-${style}.woff2`);
    const buf = fs.readFileSync(file);
    total += buf.length;
    const b64 = buf.toString('base64');
    css += `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};`
         + `font-display:swap;src:url(data:font/woff2;base64,${b64}) format('woff2');}\n`;
  }
}

const block =
  '<!-- VENDORED-FONTS:START — generated by scripts/vendor-fonts.mjs; do not hand-edit -->\n'
  + '<style>\n' + css + '</style>\n'
  + '<!-- VENDORED-FONTS:END -->';

let html = fs.readFileSync(APP, 'utf8');

// 1a. First run: swap the Google Fonts preconnects + stylesheet link for the block.
const googleBlock = /[ \t]*<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com">\r?\n[ \t]*<link rel="preconnect" href="https:\/\/fonts\.gstatic\.com"[^>]*>\r?\n[ \t]*<link href="https:\/\/fonts\.googleapis\.com\/css2[^>]*>/;
// 1b. Re-run: swap a previously generated block.
const existing = /<!-- VENDORED-FONTS:START[\s\S]*?VENDORED-FONTS:END -->/;

if (existing.test(html)) {
  html = html.replace(existing, block);
} else if (googleBlock.test(html)) {
  html = html.replace(googleBlock, block);
} else {
  console.error('✗ Could not find the Google Fonts block or an existing VENDORED-FONTS block.');
  process.exit(1);
}

// 2. Point model-viewer at the local vendored copy (idempotent).
const mv = /<script type="module" src="[^"]*model-viewer\.min\.js"><\/script>/;
if (!mv.test(html)) {
  console.error('✗ Could not find the model-viewer <script type="module"> tag.');
  process.exit(1);
}
html = html.replace(mv, '<script type="module" src="assets/vendor/model-viewer.min.js"></script>');

fs.writeFileSync(APP, html);
console.log(`✓ Inlined ${FONTS.reduce((n, f) => n + f[2].length, 0)} woff2 faces `
  + `(${(total / 1024).toFixed(0)} KB raw) and pointed model-viewer at assets/vendor/.`);
